feature-hw-2
kristina-salnyk/node-js-course-practice pull request #2
Opened 2023-10-12 17:10 UTC by kristina-salnyk

Refactor an existing application to use TypeScript

2023-10-17 12:29 UTC, KryvDanylo reviewed
Also, it would be great if you added prettier config

2023-10-17 12:29 UTC, KryvDanylo commented on src/middlewares/validateBody.ts
> +      const e = new Error('Invalid input') as ApiError;
You can create a class ApiError extended from Error and avoid using "as".

2023-10-17 16:13 UTC, kristina-salnyk commented
> Also, it would be great if you added prettier config

Configured Prettier, and added general formatting rules. Additionally, configured pre-commit validation using Husky.

2023-10-17 16:14 UTC, kristina-salnyk commented on src/middlewares/validateBody.ts
> +      const e = new Error('Invalid input') as ApiError;
Yea, of course, changes have been added.

2023-10-17 16:15 UTC, kristina-salnyk commented
@KryvDanylo, please check changes

2023-10-18 10:16 UTC, KryvDanylo requested changes

2023-10-18 10:16 UTC, KryvDanylo commented on src/classes/ApiError.ts
> +class ApiError extends Error {
Good, but a better name for the folder would be errors.

2023-10-18 10:19 UTC, kristina-salnyk commented on src/classes/ApiError.ts
> +class ApiError extends Error {
Fixed

2023-10-18 10:28 UTC, KryvDanylo approved these changes
Good

2023-10-18 10:56 UTC, merged